# NUMPY Assignment

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
np.show_config()

1.17.3
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [88]:
b=np.array([1,2,3])
# print(b.data)    #memory address of "b"
print(b.size*b.itemsize,"bytes") 
# bcoz for each int 4 bytes total 3 int so total 12 bytes

12 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
# help(np.add) 'or'
np.info(np.add)  # both work

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None`

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
b=np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [12]:
a=np.arange(10)
print(a,"\n")
a=a[::-1]
print(a)

[0 1 2 3 4 5 6 7 8 9] 

[9 8 7 6 5 4 3 2 1 0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [14]:
b=np.matrix(np.arange(9).reshape(1,3,3))
b

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [15]:
a=np.array([1,2,0,0,4,0])
print(np.nonzero(a))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [16]:
a=np.matrix(np.eye(3))
a        # matrix

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
a=np.random.random((3,3,3))
a

array([[[0.90047957, 0.99375732, 0.79325222],
        [0.57124629, 0.94806355, 0.69800638],
        [0.2790959 , 0.20319434, 0.38874161]],

       [[0.97397463, 0.82678844, 0.3264238 ],
        [0.23364709, 0.96619011, 0.81952974],
        [0.9681396 , 0.45636381, 0.13030615]],

       [[0.14238447, 0.17491047, 0.58392191],
        [0.65542249, 0.85888597, 0.76815045],
        [0.88637576, 0.43852155, 0.39883559]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
a=np.random.randn(10,10)
#print(a)
print(np.min(a))
print(np.max(a))

-2.8788489440468346
2.881014142392129


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
b=np.random.random(30)
print(np.mean(b))

0.491644044276803


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
a=np.ones((4,4))
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [40]:
b=np.ones((5,5))
b=np.pad(b,pad_width=1,mode='constant',constant_values=0)
b

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [62]:
print(0*np.nan)       # any value multiply with "nan" is =nan
print(np.nan==np.nan) # nan means "None", this is not value , so False
print(np.inf>np.nan)  # 
print(np.nan-np.nan)  # this is not value , always got "nan" in perform operation on nan with arithmetic operators
print(np.nan in set([np.nan]))  # set have nan elemnt so condition True
print(0.3==3*0.1)        # not equal bcoz in 3*01 , we not got exactly 0.3, bcoz of some error in performing operation

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [43]:
# x = np.arange(9).reshape((3,3))
# k positive means (0,k)  , k negative means (k,0)
# print(x)
# print(np.diag(x))      # diagonal start from bydefault (0,0) index
# print(np.diag(x,k=1))  #doagonal start from (0,1) elemnt
# print(np.diag(x,k=2))  # diagonal start from (0,2)

a=np.diag(np.arange(1,5),k=-1) # k negative means kth row (1st row)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [46]:
a=np.ones((8,8),dtype=int)
a[::2,1::2]=0
a[1::2,::2]=0
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [51]:
a=np.arange(336).reshape(6,7,8)
#np.ravel_multi_index(99,(6,7,8))
np.unravel_index(99,(6,7,8))
# bcoz we start from 0 so 99 is the 100th element

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [58]:
a=[[0,1],[1,0]]
np.tile(a,(4,4)) # tile means there [[0,1],[1,0]] treat as a one value on one elements
# (4,4) means put a tile "a" into 4X4 matrix

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

# $Normalize$=(X-Mean(X))/Standard deviation(X)

In [97]:
x=np.random.randn(5,5)
y=(x-np.mean(x))/(np.std(x))
print(y)

[[-0.82951411  0.02650955 -0.51732097  1.18732556 -1.08053057]
 [-0.04014821  1.20990216  1.21535049  1.45835368  1.08877558]
 [ 0.11298504  0.47286066 -0.28402855 -1.9561311   0.39762091]
 [ 0.45244034 -1.33808871 -2.01725353 -0.33396518  0.33156248]
 [-1.27247342  1.69045188 -0.26867872  0.27298469  0.02101005]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [60]:
a=np.arange(15).reshape(5,3)
b=np.arange(6).reshape(3,2)
print(np.dot(a,b))
a@b

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [63]:
a=np.arange(15)

a[(a>3) & (a<8)]+=10      # >3 and <8  no add with 10
# a[(a>3) | (a<8)]+=10  
a

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [64]:
print(sum(range(5),-1))# (9 output) -1 subtract from total sum

9


In [62]:
from numpy import *      # it import all the definitons n functions from the module numpy
print(sum(range(5),-1)) #(10 output) bcoz we import all the definitions

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

## $0^0=1$

In [200]:
z=np.arange(4)
print(z)
print(z**z)  # 0^0=1
print(2<<z>>2)  #2<<3  means 2 shift to lef side 3 time we got 16  16>>2 , 16 right shift to 2 times
print(z<-z)
print(1j*z) # multiply with 0+1j so real value we got zero, only imaginary value print
print(z/1/1)
# print(z<z>z)  # we got error we cany use this type, this is the right syntax of using this (z<z) | (z>z)

[0 1 2 3]
[ 1  1  4 27]
[0 1 2 4]
[False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j]
[0. 1. 2. 3.]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [72]:
a=np.array(0)
print(a/a)  # 0/0
print(a//a)  # 0//0=0  remove decimal
np.array([np.nan]).astype(int).astype(float) # convert "nan" into 'int' data type first then, converted into 'float' data type

nan
0


c:\users\patid\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
c:\users\patid\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [81]:
a=np.linspace(-3,3,20)
# print(a)
print(np.ceil(a))
print(np.floor(a))

[-3. -2. -2. -2. -1. -1. -1. -0. -0. -0.  1.  1.  1.  2.  2.  2.  3.  3.
  3.  3.]
[-3. -3. -3. -3. -2. -2. -2. -1. -1. -1.  0.  0.  0.  1.  1.  1.  2.  2.
  2.  3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [85]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,4,3]])
np.intersect1d(a,b)  # common elements b/w arrays n we always got result in 1D array
# no need of same dimension array it may be ant type 1D, 2D, 3D etc.
# 1D & 2D   , 1D & 3D ,  2D & 3D  intersection is also valid

array([1, 3, 4])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [31]:
print(np.sqrt(-1))        # this is ="nan"
print(np.emath.sqrt(-1))  # this is =1j(imaginary)
np.sqrt(-1)==np.emath.sqrt(-1)
# nan==1j  ,not equal so its false

nan
1j


c:\users\patid\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.
c:\users\patid\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [69]:
# usinf datetime nodule
import datetime as dt
print("yesterday date : ",dt.date.today()-dt.timedelta(days=1))
print("today's date   : ",dt.date.today())
print("Tomorrow date  : ",dt.date.today()+dt.timedelta(days=1))

yesterday date :  2019-11-01
today's date   :  2019-11-02
Tomorrow date  :  2019-11-03


In [64]:
# using numpy
a=np.datetime64('today')
b=np.datetime64('today')-np.timedelta64(1)
c=np.datetime64('today')+np.timedelta64(1)
print("yesterday date : ", b)
print("todays date    : ", a)
print("tomorrow date  : ",c)

yesterday date :  2019-11-01
todays date    :  2019-11-02
tomorrow date  :  2019-11-03


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [87]:
a=np.arange('2016-07-01','2016-08',dtype='datetime64')
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [117]:
# means we can not used 3rd variable to copy the results
# all operation with A n B only

a=np.eye(3)
b=np.ones((3,3))
np.add(a,b,out=b)      # a+b store in "b" bcoz we need "a " to store next operation result
np.divide(-a,2,out=a)  # -a/2 store in "a"
np.multiply(a,b,out=a) # "b"=a+b  and "a"=(-a/2)

array([[-1., -0., -0.],
       [-0., -1., -0.],
       [-0., -0., -1.]])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [66]:
a=np.array([-1.2,-0.7,-0.2,0.2,0.7,1.2])

print(a//1)
print(np.floor(a))
print(np.ceil(a))
print(np.trunc(a))
print(a.astype(int))


[-2. -1. -1.  0.  0.  1.]
[-2. -1. -1.  0.  0.  1.]
[-1. -0. -0.  1.  1.  2.]
[-1. -0. -0.  0.  0.  1.]
[-1  0  0  0  0  1]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [125]:
a=np.zeros((5,5))
a+=[[0,1,2,3,4]]
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [93]:
def generator():
    for b in range(10):
        yield b
a=np.fromiter(generator(),int)
print(a)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [96]:
a=np.linspace(0,1,11,endpoint=False)
a[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [138]:
a=np.random.randn(10)
a.sort()
print(a)

[-1.05409816 -1.0167525  -0.72910163 -0.52867705  0.18048611  0.33359064
  0.47380102  0.58898342  0.69108644  2.17114612]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [98]:
a=np.array([1,2,3,4,5,6,7,8,9])
np.add.reduce(a)  # reduce property of add recue the time as compare to np.sum

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [149]:
a=np.random.random((2,2))
b=np.random.random((2,2))
# np.random.randint(0,2,5)
print(a is b)     # both have not same values bcoz those generate random value
np.array_equal(a,b)

False


False

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [91]:
# Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
a = np.random.random((10,2))
b,c = a[:,0], a[:,1]  # take 1st column in b and 2nd column in c 
# b and c are now vectors
# print(b+c)(b-c)(b*c)(b/c)(b//c)  all r also converted into polar

e = np.sqrt(b+c)    # polar or scalar
f = np.arctan2(c,b) # polar or scalar
g=np.arctan(c,b)

print(e,"\n")
print(f,"\n")
print(g,"\n")

[1.2352552  0.90049634 0.94569655 1.09126407 1.14571452 1.35492281
 0.90812171 1.14251681 0.69875342 0.908795  ] 

[1.01513005 0.6697204  0.68938288 0.97126429 1.02593865 0.73577792
 1.28371188 1.23089531 1.5522415  0.21346677] 

[0.75519451 0.34408111 0.3840387  0.61566911 0.68521428 0.7173122
 0.56697162 0.76724243 0.44700039 0.14608867] 



#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [175]:
a=np.random.randn(10)
print(a,"\n")
a[np.argmax(a)]=0
print(a)

[ 1.66990149 -1.63913237  1.12683666 -1.43210526 -3.61983132  0.83126966
  0.11179877  1.19940416 -0.09280601  0.12238821] 

[ 0.         -1.63913237  1.12683666 -1.43210526 -3.61983132  0.83126966
  0.11179877  1.19940416 -0.09280601  0.12238821]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [16]:
x=np.array([5,6,7,8])
y=np.array([1,2,3,4])
z=np.zeros((1,4))
p=0
for i in range(len(x)):
    for j in range(len(y)):
        z[p][j]=1/(np.subtract(x[i],y[j]))
z

array([[0.14285714, 0.16666667, 0.2       , 0.25      ]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [17]:
a=np.arange(12).reshape(4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [185]:
a=np.arange(10,dtype=np.float32)
print(a)
a=a.astype(dtype=np.int32)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [60]:
a=np.arange(4).reshape(2,2)
for index in np.ndindex(2,2):
    print(index,a[index])

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3


In [56]:
a=np.arange(4).reshape(2,2)
for index, value in np.ndenumerate(a):
    print(index,value)

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3


In [61]:
z=np.arange(4).reshape(2,2)
for i in range(z.ndim):
    for j in range(z.ndim):
        print("(%s, %s) %s"%(i,j,z[i][j]))

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [69]:
a=np.arange(1,5).reshape(2,2)
b=a-a.mean(axis=1)
print(b)

[[-0.5 -1.5]
 [ 1.5  0.5]]


#### 59. How to sort an array by the nth column? (★★☆)

In [201]:
a=np.random.randn(3,3)
print(a,"\n")
print(a[a[:,1].argsort()])

[[-1.6324911  -0.02450125 -0.62754315]
 [-0.56877906  0.17406718 -1.51549134]
 [ 0.61306613 -0.14266017  1.85323734]] 

[[ 0.61306613 -0.14266017  1.85323734]
 [-1.6324911  -0.02450125 -0.62754315]
 [-0.56877906  0.17406718 -1.51549134]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [79]:
x=[1,2,3,4,5,6,7,8,9]   # vector
i=[1,6,7,1,2,2,10,5,6]  # list
f=np.bincount(i,x)  # we store like f[i] ,where i is the index, correcpondence to index, we got the value in vector x
f                   # like f[1], we got 2 one index , so correcspondence to index at 1st 1 index value is "1" and for 2nd 1 index we got value "4"  f[1]=1+4=5
# same for other index

array([ 0.,  5., 11.,  0.,  0.,  8., 11.,  3.,  0.,  0.,  7.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [222]:
a=np.arange(16).reshape(2,2,2,2)
print(a)
print(a.sum(axis=(-1,-2)))  # numpy=1.17.0   u can pass more than one axis in tuple

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
[[ 6 22]
 [38 54]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

In [228]:
a=np.random.random((2,2))
b=np.random.random((2,2))
print(np.dot(a,b),"\n")
np.diag(np.dot(a,b))

[[0.99679567 0.20483028]
 [0.67762187 0.06748109]] 



array([0.99679567, 0.06748109])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [80]:
a=[1,2,3,4,5]
n=3   # consecutive 3 zero between each value

# create a zeros array n put our value after each three zero
z=np.zeros(len(a)+(len(a)-1)*n) # a length is 5, we put only 4 time three zero b/e them so (len(a)-1)*3 ,bcoz 3 zero

# now add our value from start n thn after each three zeros
z[::n+1]=a # start from 0 index , out increment is 4 bcox we alaso calculate value n three zero 
z


array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [84]:
a=np.arange(75).reshape(5,5,3)
b=np.ones((5,5))*3

a*b[:,:,None]  # at multiply time comparing (5,5,3) to (5,5,None) , if we not given None for compare for perform operation , it will cause error

array([[[  0.,   3.,   6.],
        [  9.,  12.,  15.],
        [ 18.,  21.,  24.],
        [ 27.,  30.,  33.],
        [ 36.,  39.,  42.]],

       [[ 45.,  48.,  51.],
        [ 54.,  57.,  60.],
        [ 63.,  66.,  69.],
        [ 72.,  75.,  78.],
        [ 81.,  84.,  87.]],

       [[ 90.,  93.,  96.],
        [ 99., 102., 105.],
        [108., 111., 114.],
        [117., 120., 123.],
        [126., 129., 132.]],

       [[135., 138., 141.],
        [144., 147., 150.],
        [153., 156., 159.],
        [162., 165., 168.],
        [171., 174., 177.]],

       [[180., 183., 186.],
        [189., 192., 195.],
        [198., 201., 204.],
        [207., 210., 213.],
        [216., 219., 222.]]])

#### 72. How to swap two rows of an array? (★★★)

In [249]:
a=np.arange(9).reshape(3,3)
print(a,"\n")
# a[:,[0,1]]=a[:,[1,0]]  # column swap
a[[0,1]]=a[[1,0]]     # row swap
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[3 4 5]
 [0 1 2]
 [6 7 8]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [89]:
a=np.linspace(-20,20,39)
print(-(a))
#np.negative(a,out=a)

[ 20.          18.94736842  17.89473684  16.84210526  15.78947368
  14.73684211  13.68421053  12.63157895  11.57894737  10.52631579
   9.47368421   8.42105263   7.36842105   6.31578947   5.26315789
   4.21052632   3.15789474   2.10526316   1.05263158  -0.
  -1.05263158  -2.10526316  -3.15789474  -4.21052632  -5.26315789
  -6.31578947  -7.36842105  -8.42105263  -9.47368421 -10.52631579
 -11.57894737 -12.63157895 -13.68421053 -14.73684211 -15.78947368
 -16.84210526 -17.89473684 -18.94736842 -20.        ]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

In [257]:
a=np.array([2,1,1,3,4,1,2,5,2,2,1,7,8,9])
print(np.bincount(a).argmax()) # if we have 2 value with same frequent then minimum value b/w them print

1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)