# -----*******[ PYTHON NUMPY Assignment Solution ]*******------
==============================================================================================================

## 1. Which of the following statement is true? 

### a. python is a high level programming language
### b. python is a interpreted language
### c. python is an object-oriented language
### d. All of the above

##  Ans(1) = All of the above

## 2. What is used to define a block of code(body of loop, function etc.) in python? 

### a. Curly braces
### b. parenthesis
### c. indentation
### d.quotation

## Ans(2)= Indentation

## 3. Which of the following is Correct?

### a. Comments are for programmers for better understanding of the program
### b. python interpreter ignores comment
### c. you can wrtie multi-line comments in python using triple quotes,eithere ''' or """
### d. All of above

## Ans(3)= All of above 

## 4. Which of the following is Correct?

### a. variable name can start with an underscore
### b. variable name can start with digit
### c. keywords can not be used as a variable name
### d. variable names can have symbol like: @,#,$ etc

## Ans(4)=  variable name can start with an underscore

## 5. In the following code, 'n' is a/an ___ ?
### n='5'

### a. Integer
### b. String
### c. Tuple
### d. operator

## Ans(5) : String

## 6. What is the output of the following code
### print(1,2,3,4,sep='#')

### a. 1 2 3 4
### b. 1234
### c. 1#2#3#4
### d. 24

## Ans(6)=    1#2#3#4 

## 7. What is used to take input from the user in python?

### a. cin
### b. scanf()
### c. input()
### d. <>

## Ans(7)= input()

## 8. What is the output of the following code??
### n = [2, 3, 4]
### print(n)

### a. 2,3,4
### b. 2 3 4
### c. [2,3,4]
### d. [2 3 4]

## Ans(8)= [2,3,4]

## 9. What is the output of the following code??
### print(3 >= 3)

### a. 3 >= 3
### b. True
### c. False
### d. None

## Ans(9)= True

## 10. The statement using 'and' operator results True if ____?

### a. both operands are true
### b. both operands are false
### c. either of the operands is true
### d. first operand is true

## Ans(10)= Both operands are true

## 11. Remove the correct number form the list x
### x=[9,2,8,4,5]
### x__?
### print(x)
### output : [9,2,8,4]

## Ans(11)= x.pop()  and  x.remove(5)

## 12. What is the output of the following code??
### import numpy as np
### x=np.array([3,4,True,False,"5.2"])
### print(x)
------------------------------------------

#### Select the output :

### a. ['3' '4' 'False' 'True' '5.2']
### b. [3. 4. 0. 1. 5.2]
### c. ['3' '4' 'True' 'False' '5.2']

## Ans(12)=  ['3' '4' 'True' 'False' '5.2'] 

## 13. Which of the following commands does not copy the refrence of the list 'x' to 'y' ??
-----------------------------------------

### a. y=x
### b. None of the options
### c. y=list(x)

## Ans(13)= y=list(x)

## 14. Complete the code to return the output
### x=True
### print(__(x))
--------------------------------
#### output : 
## 1
--------------------------------------------------------

### a. float
### b. num
### c. bool
### d. int

## Ans(14)= int

## 15. Complete the code to return the output?
### import numpy as np
### x=np.array([6,7,6,5])
### y=np.array([1,6,7,8])
### print(___?(x,y))
---------------------------------------
#### output :
## [[1.         -0.26261287]
##  [-0.26261287  1. ]]
-----------------------------------------

### a. np.corrcoef
### b. np.corr
### c. np.correlation

## Ans(15)= np.corrcoef

## 16. select the code to return the output??
### [[6]
###  [6]]
------------------------------------------

#### select the code

### (a).
### import numpy as np
###      z=np.array([[6,4,9],[6,1,1]])
###      print(z[0:,:1])
--------------------------------------

### (b).
### import numpy as np
###      z=np.array([[6,4,9],[6,1,1]])
###      print(z[0:,:2])
--------------------------------------

### (c).
### import numpy as np
###      z=np.array([[6,4,9],[6,1,1]])
###      print(z[0:,1:])

## Ans(16)= (A)

## 17. Complete the code to return the output?
-----------------------------
### p=[["X","Y",0],[3,9,6],["Z",15,10]]
### print(p[0][__?])
### Output : 
## ['y',0]
--------------------------------------

### a. 1
### b. 0
### c. :2
### d. 2
### e. 1:

## Ans(17)= 1:

## 18. Complete the code to return the output?
### p=['u','w','g','q','r','w']
### del(p[__?])
### print(p)
### Output :
### ['u','q','r','w']
-------------------------------------------

### a. 0
### b. 3:5
### c. 3
### d. 2:4
### e. 1:3
### f. 6

## Ans(18)= [1:3]

## 19. Complete the code to return the output?
### p=[9,15,5,1,3,13]
### print(sorted(p,reverse=_??))
### output :
### [1,3,5,9,13,15]
-------------------------------------------

#### fill in the blanks
### a. False
### b. True
### c. ordered
### d. p

## Ans(19)= False

## 20. Complete the code to return the output?
### import numpy as np
### store=np.array([8,2,1,5])
### cost=np.array([80,70,63,84])
### np_cols=_____?((store,cost))
### print(np_cols)
-------------------------------------------
#### required output :
### [[8 80]
###  [2 70]
### [1 63]
### [5 84]]

## Ans(20)= np_cols=np.column_stack((store,cost))

## 21. What is the output of the following command??
### [1,0,1]+[2,4,6]
-------------------------------------------

#### output :
### a. [3,4,7]
### b. 14 
### c. [1,0,1,2,4,6]
### d. 3

## Ans(21)= [1,0,1,2,4,6]

## 22. Complete the code to return the output?
### # Find the means of the first column of costs
-------------------------------------------
### import numpy as np
### costs=np.column_stack(([1,1,2,1],[5,7,7,5]))
### mean_costs=np.mean(costs___??)
### print(mean_costs)
-------------------------------------------
### output ::
### 1.25
-------------------------------------------

#### fill in the blanks
### a. [:, 0]
### b. [0, :]
### c. [1, :]
### d. [:, 1]

## Ans(22)= Cost[:,0]

## 23. Which command opens up the-documentation from inside the IPython shell for the "len()" function ??
-------------------------------------------

#### select the correct answer

### a. find(len())
### b. help(len)
### c. help(len())
### d. doc(len())

## Ans(23)= help(len)

## 24. Complete the code to return the output?
### import numpy as np
### x=np.array([4,5,6,5,2])
### bool_x=x________??3
### print(bool_x)
-------------------------------------------

#### Required output
### [True True True True False]

## Ans(24)= bool_x=x>=3

## 25. Complete the code to return the output?
### q=[21,7,19,28,13,25]
### print(___??(q))
-------------------------------------------
### output :: 28
-------------------------------------------

#### fill in the blanks
### a. length
### b. maximum
### c. min
### d. max
### e. minimum
### f. len

## Ans(25)= MAX

## 26. Complete the code to return the output?
#### Find the standard deviation of x
-------------------------------------------
### import numpy as np
### x=np.array([4.28,2.58,3.38])
### print(_______??(x))
-------------------------------------------
#### Required output ::
### 0.6944222218666554

## Ans(26)= print(np.std(x))

## 27. Complete the code to return the output?
-------------------------------------------
### Expected output :  [12 2 0]
-------------------------------------------
#### select the code
### (a)
### import numpy as np
### m=np.array([6,2,4]
### n=np.array([2,True,False])
### print(m*n)
-------------------------------------------
### (b)
### import numpy as np
### m=np.array([6,2,4]
### n=np.array([2,True,False])
### print(m-n)
-------------------------------------------
### (c)
### import numpy as np
### m=np.array([6,2,4]
### n=np.array([2,True,False])
### print(m+n)

## Ans(27)= (A)

## 28. Complete the code to return the output?
### import numpy as np
### x=np.array(['a','z','e','v'])
### print(x[___??])
-------------------------------------------
#### output ::
## ['a' 'z' 'e' 'v']
-------------------------------------------

#### Fill in the blanks
### a. 0:2
### b. 0:4
### c. 1:3
### d. 0:3
### e. 1:4
### f. 2:4

## Ans(28)= [0:4]

## 29. Complete the code to return the output?

### a=[8.7,3.89,8.23]
### b=['i','x','y']
### c=[3,9,9]
### print(____??)
-------------------------------------------
#### output ::
### [[8.7,3.89,8.23],[3,9,9],['i','x','y']]
-------------------------------------------

#### Fill in the blanks
### a. [b,c,a]
### b. [a,c,b]

## Ans(29)= [a,c,b]

## 30. Complete the code to return the output?

### x=[1,2,3,4]
### y=x
### y[1:3]=[5,6]
### print(x)
-------------------------------------------

#### correct answer
### a. [1,2,5,6]
### b. [5,6,3,4]
### c. [1,2,3,4]
### d. [1,5,6,4]

## Ans(30)= [1,5,6,4]

## 31. Complete the code to return the output?

### p=[[9,17,11],[10,15,4],["X","Y",12]]
### print(p[1][___??])
-------------------------------------------
#### required output ::
### 4

## Ans(31)= print(p[1][2])

## 32. Complete the code to return the output?

### q=[21,7,19,28,13,25]
### print(____?(q))
------------------------------------------
#### required output ::
### 28

## Ans(32)= print(max(q))

## 33. Complete the code to return the output?

### import numpy as np
### z=np.array([[0,4,15],[26,7,22]])
### print(z[0][2])
------------------------------------------
#### OUTPUT ::

## Ans(33)= 15

## 34. Complete the code to return the output?

### z="authorize"
### print(z.____?("o","*"))
------------------------------------------
#### output ::
### auth*rize

## Ans(34)= print(z.replace("o","*"))

## 35. Complete the code to return the output?
------------------------------------------
### [6,10,14,2,6,18]
------------------------------------------

#### Select the code
### (a)
### x=[6,10,14,2,6,18,17]
### print(x[0:4])
------------------------------------------
### (b)
### x=[6,10,14,2,6,18,17]
### print(x[2:5])
------------------------------------------
### (c)
### x=[6,10,14,2,6,18,17]
### print(x[0:6])

## Ans(35)= (C)

## 36. Complete the code to return the output?
### x=8
### y=9
### z=2
### print(____??)
------------------------------------------
#### output ::
### [2,9,8]
------------------------------------------

#### fill in the blanks
### a. [z,y,x]
### b. [x,y,z]

## Ans(36)= [z,y,x]

## 37. Complete the code to return the output?
### y="python is a general purpose progamming language"
### print(y__________??)
------------------------------------------
#### required output ::
### Python is a general purpose programming language

## Ans(37)= print(y.capitalize())

## 38. Complete the code to return the output?
------------------------------------------
### import numpy as np
### store=np.array(["X","X","Y","Y"])
### cost=np.array([7,9,2,9])
### select_cost=cost[store_______?? "Z"]
### print(select_cost)
------------------------------------------
#### required output ::
### [7 9 2 9]

## Ans(38)= select_cost=cost[store!="Z"]

## 39. What is the output pf this code??
-----------------------------------------
### import numpy as np
### m=np.array([2,6,4])
### n=np.array([2,True,False])
### print(m**n)
---------------------------------------
#### output ::

## Ans(39)= [4 6 1]

## 40. Complete the code to return the output?
---------------------------------------
### q=8.43999
### print(round(q,______??))
-----------------------------------------
#### required output ::
## 8.4

## Ans(40)= print(round(q,1))

## 41. Complete the code to return the output?
---------------------------------------
### import numpy as np
### x=np.array(['m','c','c','z'])
### print(x[__??])
----------------------------------------
#### output ::
## ['c','c']


## Ans(41)= print(x[1:3])

## 42. Complete the code to return the output?
----------------------------------------
### p=4
### q='the valuye of p is :'
### print(q+str(_____??))
----------------------------------------
#### output ::
### the value of p is : 4
--------------------------------------

#### fill in the blanks
### a. 'q'
### b. p
### c. 'p'
### d. q

## Ans(42)=  print(q+str(p)) 

## 43. What are the optional argument to the function 'function_1()' ??


------------------------------------------
### function_1(r1,q,p=None,r2=None)

## Ans(43)= "P" and "r2" are the optional argument

## 44. Complete the code to return the output?
-----------------------------------------
### a=[4.72,6.77,3.51]
### b=['y','v','c']
### c=[7,3,3]
### print(_____??)
------------------------------------------
#### output ::
### [[7,3,3],['y','v','c'],[4.72,6.77,3.51]]

## Ans(44)=  [c,b,a]

## 45. What is the output of this code??
------------------------------------------
### x=[9,14,9,19,12,11,12]
### print(x[2:6])

## Ans(45)=  [9,19,12,11]